bankaccountdb:
 image: mongo:latest
 restart: always
 container_name: "bankaccountdb"
 ports:
  - "27017:27017"

bankaccountservice:
 build: .
 dockerfile: Dockerfile
 container_name: bankaccountservice
 ports:
  - "8081:8080"
 links:
  - bankaccountdb
 